AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - org.fintracker::auth
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "fintracker-auth-${Env}"
      Handler: com.fintracker.auth.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      AutoPublishAlias: live
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  AuthApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Env}/auth/info'
    Export:
      Name: !Sub "${AWS::StackName}-AuthApi"
